services:
  exporter:
    build: .
    ports:
      - "9109:9109"
    volumes:
      - ./data:/app/data

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - exporter

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "3001:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

  webapi:
    build: ./webapi
    ports:
      - "8000:8000"
    depends_on:
      - exporter
      - prometheus


volumes:
  grafana-storage:
