name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y aide rkhunter iproute2 iptables

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r python/requirements.txt -r dev-requirements.txt

      - name: Lint (flake8)
        run: flake8 python/ scripts/

      - name: Format check (black)
        run: black --check python/ scripts/

      - name: Run tests
        run: pytest -q
